dtdevdoc-8406-hosted-card-fields-update
paypal-examples/docs-examples pull request #87
Opened 2023-10-16 20:00 UTC by devapplepaypal

* Promoted `/advanced-integration/beta` to `/advanced-integration/v2`.
* Cleaned up the `/advanced-integration` folder.
* Updated the `README.md` for both `/advanced-integration/v1` and `/advanced-integration/v2`.

2023-10-16 20:04 UTC, gregjopa commented on advanced-integration/README.md
> +* `v1` contains sample code for the legacy advanced Checkout integration. Use `v2` for new integrations.
```suggestion
* [v1](v1/README.md) contains sample code for the legacy advanced Checkout integration. Use `v2` for new integrations.
```

2023-10-16 20:47 UTC, MALIKSHAHID786 commented
> Jira ticket: https://paypal.atlassian.net/browse/DTDEVDOC-8406
> 
> * Promoted `/advanced-integration/beta` to `/advanced-integration/v2`.
> * Cleaned up the `/advanced-integration` folder.
> * Updated the `README.md` for both `/advanced-integration/v1` and `/advanced-integration/v2`.

2023-10-18 13:28 UTC, e-tu requested changes

2023-10-18 13:28 UTC, e-tu commented on advanced-integration/README.md
> +This folder contains example code for an advanced Checkout PayPal integration using both the JavaScript SDK and Node.js to complete transactions with the PayPal REST API.
```suggestion
This folder contains example code for a PayPal advanced Checkout integration using both the JavaScript SDK and Node.js to complete transactions with the PayPal REST API.
```

2023-10-18 13:28 UTC, e-tu commented on advanced-integration/v1/README.md
> +This folder contains example code for [version 1](https://developer.paypal.com/docs/checkout/advanced/integrate/sdk/v1) of an advanced Checkout PayPal integration using the JavaScript SDK and Node.js
```suggestion
This folder contains example code for [version 1](https://developer.paypal.com/docs/checkout/advanced/integrate/sdk/v1) of a PayPal advanced Checkout integration using the JavaScript SDK and Node.js to complete transactions with the PayPal REST API.
```

2023-10-18 13:28 UTC, e-tu commented on advanced-integration/v2/README.md
> +This folder contains example code for [version 2](https://developer.paypal.com/docs/checkout/advanced/integrate/) of an advanced Checkout PayPal integration using the JavaScript SDK and Node.js to co
```suggestion
This folder contains example code for [version 2](https://developer.paypal.com/docs/checkout/advanced/integrate/) of a PayPal advanced Checkout integration using the JavaScript SDK and Node.js to complete transactions with the PayPal REST API.
```

2023-10-18 13:28 UTC, e-tu commented on advanced-integration/v2/README.md
> +Version 2 is the current advanced Checkout integration, and includes Hosted Card Fields.
```suggestion
Version 2 is the current advanced Checkout integration, and includes hosted card fields.
```

2023-10-18 13:28 UTC, e-tu commented on advanced-integration/v2/README.md
> +The documentation for advanced Checkout integration using JavaScript SDK includes additional sample code in the following sections:
```suggestion
The documentation for an advanced Checkout integration using the JavaScript SDK includes additional sample code in the following sections:
```

2023-10-24 20:35 UTC, gregjopa approved these changes

2023-10-24 20:35 UTC, merged

2023-10-25 22:01 UTC, shango420 commented
> https://paypal.me/xhangtech?country.x=MX&locale.x=es_XC

2023-10-25 22:02 UTC, shango420 commented
> > https://paypal.me/xhangtech?country.x=MX&locale.x=es_XC

c4ee30fb101f3b2ea4a3665a37c7beca65fb02b5